export type Country = { code: string; ar: string; en: string; flag: string };

// Every country. Arab states are listed first (they are the app's home market),
// then the rest of the world in Arabic alphabetical order.
export const COUNTRIES: Country[] = [
  { code: "SA", ar: "السعودية", en: "Saudi Arabia", flag: "🇸🇦" },
  { code: "AE", ar: "الإمارات", en: "United Arab Emirates", flag: "🇦🇪" },
  { code: "KW", ar: "الكويت", en: "Kuwait", flag: "🇰🇼" },
  { code: "QA", ar: "قطر", en: "Qatar", flag: "🇶🇦" },
  { code: "BH", ar: "البحرين", en: "Bahrain", flag: "🇧🇭" },
  { code: "OM", ar: "عُمان", en: "Oman", flag: "🇴🇲" },
  { code: "EG", ar: "مصر", en: "Egypt", flag: "🇪🇬" },
  { code: "JO", ar: "الأردن", en: "Jordan", flag: "🇯🇴" },
  { code: "LB", ar: "لبنان", en: "Lebanon", flag: "🇱🇧" },
  { code: "SY", ar: "سوريا", en: "Syria", flag: "🇸🇾" },
  { code: "IQ", ar: "العراق", en: "Iraq", flag: "🇮🇶" },
  { code: "PS", ar: "الأراضي الفلسطينية", en: "Palestinian Territories", flag: "🇵🇸" },
  { code: "YE", ar: "اليمن", en: "Yemen", flag: "🇾🇪" },
  { code: "SD", ar: "السودان", en: "Sudan", flag: "🇸🇩" },
  { code: "LY", ar: "ليبيا", en: "Libya", flag: "🇱🇾" },
  { code: "TN", ar: "تونس", en: "Tunisia", flag: "🇹🇳" },
  { code: "DZ", ar: "الجزائر", en: "Algeria", flag: "🇩🇿" },
  { code: "MA", ar: "المغرب", en: "Morocco", flag: "🇲🇦" },
  { code: "MR", ar: "موريتانيا", en: "Mauritania", flag: "🇲🇷" },
  { code: "SO", ar: "الصومال", en: "Somalia", flag: "🇸🇴" },
  { code: "DJ", ar: "جيبوتي", en: "Djibouti", flag: "🇩🇯" },
  { code: "KM", ar: "جزر القمر", en: "Comoros", flag: "🇰🇲" },
  { code: "IS", ar: "آيسلندا", en: "Iceland", flag: "🇮🇸" },
  { code: "ET", ar: "إثيوبيا", en: "Ethiopia", flag: "🇪🇹" },
  { code: "AZ", ar: "أذربيجان", en: "Azerbaijan", flag: "🇦🇿" },
  { code: "AM", ar: "أرمينيا", en: "Armenia", flag: "🇦🇲" },
  { code: "ER", ar: "إريتريا", en: "Eritrea", flag: "🇪🇷" },
  { code: "ES", ar: "إسبانيا", en: "Spain", flag: "🇪🇸" },
  { code: "AU", ar: "أستراليا", en: "Australia", flag: "🇦🇺" },
  { code: "EE", ar: "إستونيا", en: "Estonia", flag: "🇪🇪" },
  { code: "IL", ar: "إسرائيل", en: "Israel", flag: "🇮🇱" },
  { code: "SZ", ar: "إسواتيني", en: "Eswatini", flag: "🇸🇿" },
  { code: "AF", ar: "أفغانستان", en: "Afghanistan", flag: "🇦🇫" },
  { code: "AR", ar: "الأرجنتين", en: "Argentina", flag: "🇦🇷" },
  { code: "EC", ar: "الإكوادور", en: "Ecuador", flag: "🇪🇨" },
  { code: "AL", ar: "ألبانيا", en: "Albania", flag: "🇦🇱" },
  { code: "BR", ar: "البرازيل", en: "Brazil", flag: "🇧🇷" },
  { code: "PT", ar: "البرتغال", en: "Portugal", flag: "🇵🇹" },
  { code: "BA", ar: "البوسنة والهرسك", en: "Bosnia & Herzegovina", flag: "🇧🇦" },
  { code: "CZ", ar: "التشيك", en: "Czechia", flag: "🇨🇿" },
  { code: "ME", ar: "الجبل الأسود", en: "Montenegro", flag: "🇲🇪" },
  { code: "DK", ar: "الدانمرك", en: "Denmark", flag: "🇩🇰" },
  { code: "CV", ar: "الرأس الأخضر", en: "Cape Verde", flag: "🇨🇻" },
  { code: "SV", ar: "السلفادور", en: "El Salvador", flag: "🇸🇻" },
  { code: "SN", ar: "السنغال", en: "Senegal", flag: "🇸🇳" },
  { code: "SE", ar: "السويد", en: "Sweden", flag: "🇸🇪" },
  { code: "CN", ar: "الصين", en: "China", flag: "🇨🇳" },
  { code: "GA", ar: "الغابون", en: "Gabon", flag: "🇬🇦" },
  { code: "VA", ar: "الفاتيكان", en: "Vatican City", flag: "🇻🇦" },
  { code: "PH", ar: "الفلبين", en: "Philippines", flag: "🇵🇭" },
  { code: "CM", ar: "الكاميرون", en: "Cameroon", flag: "🇨🇲" },
  { code: "CG", ar: "الكونغو - برازافيل", en: "Congo - Brazzaville", flag: "🇨🇬" },
  { code: "CD", ar: "الكونغو - كينشاسا", en: "Congo - Kinshasa", flag: "🇨🇩" },
  { code: "DE", ar: "ألمانيا", en: "Germany", flag: "🇩🇪" },
  { code: "MX", ar: "المكسيك", en: "Mexico", flag: "🇲🇽" },
  { code: "GB", ar: "بريطانيا", en: "United Kingdom", flag: "🇬🇧" },
  { code: "NO", ar: "النرويج", en: "Norway", flag: "🇳🇴" },
  { code: "AT", ar: "النمسا", en: "Austria", flag: "🇦🇹" },
  { code: "NE", ar: "النيجر", en: "Niger", flag: "🇳🇪" },
  { code: "IN", ar: "الهند", en: "India", flag: "🇮🇳" },
  { code: "US", ar: "الولايات المتحدة", en: "United States", flag: "🇺🇸" },
  { code: "JP", ar: "اليابان", en: "Japan", flag: "🇯🇵" },
  { code: "GR", ar: "اليونان", en: "Greece", flag: "🇬🇷" },
  { code: "AG", ar: "أنتيغوا وبربودا", en: "Antigua & Barbuda", flag: "🇦🇬" },
  { code: "AD", ar: "أندورا", en: "Andorra", flag: "🇦🇩" },
  { code: "ID", ar: "إندونيسيا", en: "Indonesia", flag: "🇮🇩" },
  { code: "AO", ar: "أنغولا", en: "Angola", flag: "🇦🇴" },
  { code: "UY", ar: "أورغواي", en: "Uruguay", flag: "🇺🇾" },
  { code: "UZ", ar: "أوزبكستان", en: "Uzbekistan", flag: "🇺🇿" },
  { code: "UG", ar: "أوغندا", en: "Uganda", flag: "🇺🇬" },
  { code: "UA", ar: "أوكرانيا", en: "Ukraine", flag: "🇺🇦" },
  { code: "IR", ar: "إيران", en: "Iran", flag: "🇮🇷" },
  { code: "IE", ar: "أيرلندا", en: "Ireland", flag: "🇮🇪" },
  { code: "IT", ar: "إيطاليا", en: "Italy", flag: "🇮🇹" },
  { code: "PG", ar: "بابوا غينيا الجديدة", en: "Papua New Guinea", flag: "🇵🇬" },
  { code: "PY", ar: "باراغواي", en: "Paraguay", flag: "🇵🇾" },
  { code: "PK", ar: "باكستان", en: "Pakistan", flag: "🇵🇰" },
  { code: "PW", ar: "بالاو", en: "Palau", flag: "🇵🇼" },
  { code: "BB", ar: "بربادوس", en: "Barbados", flag: "🇧🇧" },
  { code: "BN", ar: "بروناي", en: "Brunei", flag: "🇧🇳" },
  { code: "BE", ar: "بلجيكا", en: "Belgium", flag: "🇧🇪" },
  { code: "BG", ar: "بلغاريا", en: "Bulgaria", flag: "🇧🇬" },
  { code: "BZ", ar: "بليز", en: "Belize", flag: "🇧🇿" },
  { code: "BD", ar: "بنغلاديش", en: "Bangladesh", flag: "🇧🇩" },
  { code: "PA", ar: "بنما", en: "Panama", flag: "🇵🇦" },
  { code: "BJ", ar: "بنين", en: "Benin", flag: "🇧🇯" },
  { code: "BT", ar: "بوتان", en: "Bhutan", flag: "🇧🇹" },
  { code: "BW", ar: "بوتسوانا", en: "Botswana", flag: "🇧🇼" },
  { code: "PR", ar: "بورتوريكو", en: "Puerto Rico", flag: "🇵🇷" },
  { code: "BF", ar: "بوركينا فاسو", en: "Burkina Faso", flag: "🇧🇫" },
  { code: "BI", ar: "بوروندي", en: "Burundi", flag: "🇧🇮" },
  { code: "PL", ar: "بولندا", en: "Poland", flag: "🇵🇱" },
  { code: "BO", ar: "بوليفيا", en: "Bolivia", flag: "🇧🇴" },
  { code: "PE", ar: "بيرو", en: "Peru", flag: "🇵🇪" },
  { code: "BY", ar: "بيلاروس", en: "Belarus", flag: "🇧🇾" },
  { code: "TH", ar: "تايلاند", en: "Thailand", flag: "🇹🇭" },
  { code: "TW", ar: "تايوان", en: "Taiwan", flag: "🇹🇼" },
  { code: "TM", ar: "تركمانستان", en: "Turkmenistan", flag: "🇹🇲" },
  { code: "TR", ar: "تركيا", en: "Türkiye", flag: "🇹🇷" },
  { code: "TT", ar: "ترينيداد وتوباغو", en: "Trinidad & Tobago", flag: "🇹🇹" },
  { code: "TD", ar: "تشاد", en: "Chad", flag: "🇹🇩" },
  { code: "CL", ar: "تشيلي", en: "Chile", flag: "🇨🇱" },
  { code: "TZ", ar: "تنزانيا", en: "Tanzania", flag: "🇹🇿" },
  { code: "TG", ar: "توغو", en: "Togo", flag: "🇹🇬" },
  { code: "TV", ar: "توفالو", en: "Tuvalu", flag: "🇹🇻" },
  { code: "TO", ar: "تونغا", en: "Tonga", flag: "🇹🇴" },
  { code: "TL", ar: "تيمور - ليشتي", en: "Timor-Leste", flag: "🇹🇱" },
  { code: "JM", ar: "جامايكا", en: "Jamaica", flag: "🇯🇲" },
  { code: "BS", ar: "جزر البهاما", en: "Bahamas", flag: "🇧🇸" },
  { code: "MV", ar: "جزر المالديف", en: "Maldives", flag: "🇲🇻" },
  { code: "SB", ar: "جزر سليمان", en: "Solomon Islands", flag: "🇸🇧" },
  { code: "MH", ar: "جزر مارشال", en: "Marshall Islands", flag: "🇲🇭" },
  { code: "CF", ar: "جمهورية أفريقيا الوسطى", en: "Central African Republic", flag: "🇨🇫" },
  { code: "DO", ar: "جمهورية الدومينيكان", en: "Dominican Republic", flag: "🇩🇴" },
  { code: "ZA", ar: "جنوب أفريقيا", en: "South Africa", flag: "🇿🇦" },
  { code: "SS", ar: "جنوب السودان", en: "South Sudan", flag: "🇸🇸" },
  { code: "GE", ar: "جورجيا", en: "Georgia", flag: "🇬🇪" },
  { code: "DM", ar: "دومينيكا", en: "Dominica", flag: "🇩🇲" },
  { code: "RW", ar: "رواندا", en: "Rwanda", flag: "🇷🇼" },
  { code: "RU", ar: "روسيا", en: "Russia", flag: "🇷🇺" },
  { code: "RO", ar: "رومانيا", en: "Romania", flag: "🇷🇴" },
  { code: "ZM", ar: "زامبيا", en: "Zambia", flag: "🇿🇲" },
  { code: "ZW", ar: "زيمبابوي", en: "Zimbabwe", flag: "🇿🇼" },
  { code: "CI", ar: "ساحل العاج", en: "Côte d’Ivoire", flag: "🇨🇮" },
  { code: "WS", ar: "ساموا", en: "Samoa", flag: "🇼🇸" },
  { code: "SM", ar: "سان مارينو", en: "San Marino", flag: "🇸🇲" },
  { code: "VC", ar: "سانت فنسنت وجزر غرينادين", en: "St. Vincent & Grenadines", flag: "🇻🇨" },
  { code: "KN", ar: "سانت كيتس ونيفيس", en: "St. Kitts & Nevis", flag: "🇰🇳" },
  { code: "LC", ar: "سانت لوسيا", en: "St. Lucia", flag: "🇱🇨" },
  { code: "ST", ar: "ساو تومي وبرينسيبي", en: "São Tomé & Príncipe", flag: "🇸🇹" },
  { code: "LK", ar: "سريلانكا", en: "Sri Lanka", flag: "🇱🇰" },
  { code: "SK", ar: "سلوفاكيا", en: "Slovakia", flag: "🇸🇰" },
  { code: "SI", ar: "سلوفينيا", en: "Slovenia", flag: "🇸🇮" },
  { code: "SG", ar: "سنغافورة", en: "Singapore", flag: "🇸🇬" },
  { code: "SR", ar: "سورينام", en: "Suriname", flag: "🇸🇷" },
  { code: "CH", ar: "سويسرا", en: "Switzerland", flag: "🇨🇭" },
  { code: "SL", ar: "سيراليون", en: "Sierra Leone", flag: "🇸🇱" },
  { code: "SC", ar: "سيشل", en: "Seychelles", flag: "🇸🇨" },
  { code: "RS", ar: "صربيا", en: "Serbia", flag: "🇷🇸" },
  { code: "TJ", ar: "طاجيكستان", en: "Tajikistan", flag: "🇹🇯" },
  { code: "GM", ar: "غامبيا", en: "Gambia", flag: "🇬🇲" },
  { code: "GH", ar: "غانا", en: "Ghana", flag: "🇬🇭" },
  { code: "GD", ar: "غرينادا", en: "Grenada", flag: "🇬🇩" },
  { code: "GT", ar: "غواتيمالا", en: "Guatemala", flag: "🇬🇹" },
  { code: "GY", ar: "غيانا", en: "Guyana", flag: "🇬🇾" },
  { code: "GN", ar: "غينيا", en: "Guinea", flag: "🇬🇳" },
  { code: "GQ", ar: "غينيا الاستوائية", en: "Equatorial Guinea", flag: "🇬🇶" },
  { code: "GW", ar: "غينيا بيساو", en: "Guinea-Bissau", flag: "🇬🇼" },
  { code: "VU", ar: "فانواتو", en: "Vanuatu", flag: "🇻🇺" },
  { code: "FR", ar: "فرنسا", en: "France", flag: "🇫🇷" },
  { code: "VE", ar: "فنزويلا", en: "Venezuela", flag: "🇻🇪" },
  { code: "FI", ar: "فنلندا", en: "Finland", flag: "🇫🇮" },
  { code: "VN", ar: "فيتنام", en: "Vietnam", flag: "🇻🇳" },
  { code: "FJ", ar: "فيجي", en: "Fiji", flag: "🇫🇯" },
  { code: "CY", ar: "قبرص", en: "Cyprus", flag: "🇨🇾" },
  { code: "KG", ar: "قيرغيزستان", en: "Kyrgyzstan", flag: "🇰🇬" },
  { code: "KZ", ar: "كازاخستان", en: "Kazakhstan", flag: "🇰🇿" },
  { code: "HR", ar: "كرواتيا", en: "Croatia", flag: "🇭🇷" },
  { code: "KH", ar: "كمبوديا", en: "Cambodia", flag: "🇰🇭" },
  { code: "CA", ar: "كندا", en: "Canada", flag: "🇨🇦" },
  { code: "CU", ar: "كوبا", en: "Cuba", flag: "🇨🇺" },
  { code: "KR", ar: "كوريا الجنوبية", en: "South Korea", flag: "🇰🇷" },
  { code: "KP", ar: "كوريا الشمالية", en: "North Korea", flag: "🇰🇵" },
  { code: "CR", ar: "كوستاريكا", en: "Costa Rica", flag: "🇨🇷" },
  { code: "CO", ar: "كولومبيا", en: "Colombia", flag: "🇨🇴" },
  { code: "KI", ar: "كيريباتي", en: "Kiribati", flag: "🇰🇮" },
  { code: "KE", ar: "كينيا", en: "Kenya", flag: "🇰🇪" },
  { code: "LV", ar: "لاتفيا", en: "Latvia", flag: "🇱🇻" },
  { code: "LA", ar: "لاوس", en: "Laos", flag: "🇱🇦" },
  { code: "LU", ar: "لوكسمبورغ", en: "Luxembourg", flag: "🇱🇺" },
  { code: "LR", ar: "ليبيريا", en: "Liberia", flag: "🇱🇷" },
  { code: "LT", ar: "ليتوانيا", en: "Lithuania", flag: "🇱🇹" },
  { code: "LI", ar: "ليختنشتاين", en: "Liechtenstein", flag: "🇱🇮" },
  { code: "LS", ar: "ليسوتو", en: "Lesotho", flag: "🇱🇸" },
  { code: "MT", ar: "مالطا", en: "Malta", flag: "🇲🇹" },
  { code: "ML", ar: "مالي", en: "Mali", flag: "🇲🇱" },
  { code: "MY", ar: "ماليزيا", en: "Malaysia", flag: "🇲🇾" },
  { code: "MG", ar: "مدغشقر", en: "Madagascar", flag: "🇲🇬" },
  { code: "MK", ar: "مقدونيا الشمالية", en: "North Macedonia", flag: "🇲🇰" },
  { code: "MW", ar: "ملاوي", en: "Malawi", flag: "🇲🇼" },
  { code: "MO", ar: "منطقة ماكاو الإدارية الخاصة", en: "Macao SAR China", flag: "🇲🇴" },
  { code: "MN", ar: "منغوليا", en: "Mongolia", flag: "🇲🇳" },
  { code: "MU", ar: "موريشيوس", en: "Mauritius", flag: "🇲🇺" },
  { code: "MZ", ar: "موزمبيق", en: "Mozambique", flag: "🇲🇿" },
  { code: "MD", ar: "مولدوفا", en: "Moldova", flag: "🇲🇩" },
  { code: "MC", ar: "موناكو", en: "Monaco", flag: "🇲🇨" },
  { code: "MM", ar: "ميانمار (بورما)", en: "Myanmar (Burma)", flag: "🇲🇲" },
  { code: "FM", ar: "ميكرونيزيا", en: "Micronesia", flag: "🇫🇲" },
  { code: "NA", ar: "ناميبيا", en: "Namibia", flag: "🇳🇦" },
  { code: "NR", ar: "ناورو", en: "Nauru", flag: "🇳🇷" },
  { code: "NP", ar: "نيبال", en: "Nepal", flag: "🇳🇵" },
  { code: "NG", ar: "نيجيريا", en: "Nigeria", flag: "🇳🇬" },
  { code: "NI", ar: "نيكاراغوا", en: "Nicaragua", flag: "🇳🇮" },
  { code: "NZ", ar: "نيوزيلندا", en: "New Zealand", flag: "🇳🇿" },
  { code: "HT", ar: "هايتي", en: "Haiti", flag: "🇭🇹" },
  { code: "HN", ar: "هندوراس", en: "Honduras", flag: "🇭🇳" },
  { code: "HU", ar: "هنغاريا", en: "Hungary", flag: "🇭🇺" },
  { code: "NL", ar: "هولندا", en: "Netherlands", flag: "🇳🇱" },
  { code: "HK", ar: "هونغ كونغ الصينية (منطقة إدارية خاصة)", en: "Hong Kong SAR China", flag: "🇭🇰" },
];

export const getCountry = (code?: string | null) => (code ? COUNTRIES.find((c) => c.code === code) : undefined);
